CC = gcc

CFLAGS = -g -Wall -O3

TARGET = client

RM = rm -f

all: $(TARGET)

$(TARGET):
	$(CC) $(CFLAGS) -c proiect.c
	$(CC) $(CFLAGS) -c client.c
	$(CC) $(CFLAGS) -o $(TARGET).x proiect.o client.o -lm

clean:
	$(RM) $(TARGET).x
